import Head from 'next/head'
import Header from '../components/header'
import styles from '../styles/Home.module.css'

export default function Home() {
  const handleOnBannerBtnClick = () =>{
    console.log("Banner button clicked!!")
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header buttonText="View stores nearby" handleOnClick={handleOnBannerBtnClick} />
      </main>

      <footer className={styles.footer}>
      rodotechnology &copy; 2022  
      </footer>
    </div>
  )
}
